VehicleFinder/urls.py
from django.contrib import admin
from django.urls import path
from app import views
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from app import views 

from django.contrib.auth.views import (
    login,
    logout,
    password_reset,
    password_reset_done,
    password_reset_confirm,
    password_reset_complete,
)

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('index/', views.index), 
    path('show',views.show),  
    path('import_csv',views.read_csv),  
    url(r'^admin/',admin.site.urls, name='admin'),
    url(r'^$', views.index, name='Home'),
    url(r'about/', views.about, name='aboutsus'),
    #url(r'contact', views.contact, name='contact'),
    url(r'rental/', views.carrent, name='carrent'),

    path('import_csv',views.read_csv),  

    #sqllite db operation
    path('dboperation',views.dboperation),  
    path('booknow',views.book_now),
    path('contactus/',views.contactus),  
    path('viewbuys',views.viewbuys),
   
    
    url(r'^vehicle/', include('app.urls')),

    url(r'^login/$',login,{'template_name': 'accounts/login.html'},name="login"),
    url(r'^logout/$',logout,{'template_name': 'accounts/logout.html'},name="logout"),
    url(r'^register/$',views.register,name='register'),
    url(r'^profile/$',views.profile,name='profile'),
    url(r'^profile/edit/$',views.edit_profile,name='edit_profile'),
    url(r'^change_password/$',views.change_password,name='change_password'),
    url(r'^password_reset/$', password_reset, name='password_reset'),
    url(r'^password_reset/done/$',password_reset_done,name='password_reset_done'),
    url(r'^password_reset_confirm/$',password_reset_confirm,name='password_reset_confirm'),
    url(r'^password_reset_complete/$',password_reset_complete,name='password_reset_complete'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = "VehicleFinder Admin"
admin.site.site_title = "VehicleFinder Admin Portal"
admin.site.index_title = "Welcome to VehicleFindePortal"

app/urls.py
from django.conf.urls import url
 
from app import views
 
app_name = 'vehicle'
 
urlpatterns = [
 
        url(r'^$', views.vehiclelist, name='index'),
        url(r'^(?P<pk>[0-9]+)/$', views.DetailsView.as_view(), name='detail'),
        
]

app/templates/about.html
{% extends "based.html" %}

{% block content %}

<style type="text/css">

 #about .glyphicon{

}

</style>

<div id="about" class="container-fluid">
  <div class="row">
    <div class="col-sm-8">
      <h2>About Company Page</h2><br>
      <h4>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</h4><br>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
      <br><button class="btn btn-default btn-lg">Get in Touch</button>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-signal logo"></span>
    </div>
  </div>
</div>



<div class="container-fluid bg-grey">
  <div class="row">
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-globe logo slideanim slide"></span>
    </div>
    <div class="col-sm-8">
      <h2>Our Values</h2><br>
      <h4><strong>MISSION:</strong> Our mission lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</h4><br>
      <p><strong>VISION:</strong> Our vision Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    </div>
  </div>
</div>



<div id="services" class="container-fluid text-center">
  <h2>SERVICES</h2>
  <h4>What we offer</h4>
  <br>
  <div class="row slideanim slide">
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-off logo-small"></span>
      <h4>POWER</h4>
      <p>Lorem ipsum dolor sit amet..</p>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-heart logo-small"></span>
      <h4>LOVE</h4>
      <p>Lorem ipsum dolor sit amet..</p>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-lock logo-small"></span>
      <h4>JOB DONE</h4>
      <p>Lorem ipsum dolor sit amet..</p>
    </div>
  </div>
  <br><br>
  <div class="row slideanim slide">
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-leaf logo-small"></span>
      <h4>GREEN</h4>
      <p>Lorem ipsum dolor sit amet..</p>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-certificate logo-small"></span>
      <h4>CERTIFIED</h4>
      <p>Lorem ipsum dolor sit amet..</p>
    </div>
    <div class="col-sm-4">
      <span class="glyphicon glyphicon-wrench logo-small"></span>
      <h4 style="color:#303030;">HARD WORK</h4>
      <p>Lorem ipsum dolor sit amet..</p>
    </div>
  </div>
</div>





<div class='container'>
  
    <div id='content' class='row-fluid'>
   
      <div class='span8 main'>
        <h2>Main Content Section</h2>
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum.<p> 

        <p>Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum.</p>
      </div>
      <div class='span2 sidebar'>
        <h3>Right Sidebar</h3>
        <ul class="nav nav-tabs nav-stacked">
          <li><a href='#'>Another Link 1</a></li>
          <li><a href='#'>Another Link 2</a></li>
          <li><a href='#'>Another Link 3</a></li>
        </ul>
      </div>
    </div>
  </div>
</body>


{% endblock %}

app/templates/based.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block title %}<title> VehicalFinder</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% load static %}
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/index/">VehicalFinder System </a>
    </div>
    <ul class="nav navbar-nav pull-right">
      <li class="active"><a  class=" fa fa-home" href="/index/">Home</a></li>
      <li><a href="/about/">About uS</a></li>
      <li><a class="fa fa-search" href="/vehicle/">vehicle Find </a></li>
      <li><a href="/contactus/"> Contact</a></li>
    

 {% if user.is_authenticated %}
                    <ul class="nav navbar-nav navbar-right">
                        
                        <li class="dropdown pdt">
                            <button class="btn" type="button" data-toggle="dropdown">Profile
                                <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                <li><a href="/profile/">View Profile</a></li>
                                <li><a href="/profile/edit/">Edit Profile</a></li>
                                <li><a href="/change_password/">Change Password</a></li>
                                <li><a href="/logout/">Logout</a></li>
                            </ul>
                        </li>
                    </ul>

         {% else %}
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="/login/">Login</a></li>
                        <li><a href="/register/">Register</a></li>
                    </ul>
                {% endif %}
    </ul>
  </div>
</nav>





  <div class="container-fluid">

    
      <div class="col-sm-12 ">
      {% block content %}{% endblock %}
      </div>
    </div>

  </div>

{% block body %}
    <h1></h1>
{% endblock %}

  <footer class=" Footer navbar-inverse"   style="color:white; padding-top:10px; padding-bottom: 10px; ">
  <div class="container-fluid">

    <center clas="active"> <h4> Made By </h4> </center> 
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-3">
        <div class="widget">
          <h5 class="widgetheading">Our Contact</h5>
          <address>
          <strong>
          </strong><br>
            tower<br>
            NewYork US.</address>
          <p>
            <i class="icon-phone"></i>  <br>
            <i class="icon-envelope-alt"></i> email@test.com
          </p>
        </div>
      </div>
      <div class="col-md-3 col-sm-3">
        <div class="widget">
          <h5 class="widgetheading">Quick Links</h5>
          <ul class="link-list">
            <li><a href="#">Latest Events</a></li>
            <li><a href="#">Terms and conditions</a></li>
            <li><a href="#">Privacy policy</a></li>
            <li><a href="#">Career</a></li>
            <li><a href="#">Contact us</a></li>
          </ul>
        </div>
      </div>
      <div class="col-md-3 col-sm-3">
        <div class="widget">
          <h5 class="widgetheading">Latest posts</h5>
          <ul class="link-list">
            <li><a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</a></li>
            <li><a href="#">Pellentesque et pulvinar enim. Quisque at tempor ligula</a></li>
            <li><a href="#">Natus error sit voluptatem accusantium doloremque</a></li>
          </ul>
        </div>
      </div>
      <div class="col-md-3 col-sm-3">
        <div class="widget">
          <h5 class="widgetheading">Recent News</h5>
          <ul class="link-list">
            <li><a href="#">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</a></li>
            <li><a href="#">Pellentesque et pulvinar enim. Quisque at tempor ligula</a></li>
            <li><a href="#">Natus error sit voluptatem accusantium doloremque</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div id="sub-footer">
    <div class="container">
      <div class="row">
        <div class="col-lg-6">
          <div class="copyright">
            <p>
              <span> 2018 All right reserved.  </span>
            </p>
          </div>
        </div>
        <div class="col-lg-6">
         
        </div>
      </div>
    </div>
  </div>

  </footer>



</body>
</html>

app/templates/car_list.html
{% extends "based.html" %}

{% block content %}

<style type="text/css">
  .w30{
    width: 200px !important;
    float: left;

    margin: 20px;
  }
  td{float: left !important;}

  .btn{
        background: green;
    color: white;
    padding: 10 10 10 10;
    width: 100px;
    padding: 8px;
  }

</style>
<script>

//custom js for book-now button
function bookme(thise){
id=thise.parentElement.parentElement.firstElementChild.textContent.slice(1);
document.location="/booknow?vid="+id
}
</script>


<script type="text/javascript">
  
  (function(document) {
  'use strict';

  var LightTableFilter = (function(Arr) {

    var _input;

    function _onInputEvent(e) {
      _input = e.target;
      var tables = document.getElementsByClassName(_input.getAttribute('data-table'));
      Arr.forEach.call(tables, function(table) {
        Arr.forEach.call(table.tBodies, function(tbody) {
          Arr.forEach.call(tbody.rows, _filter);
        });
      });
    }

    function _filter(row) {
      var text = row.textContent.toLowerCase(), val = _input.value.toLowerCase();
      row.style.display = text.indexOf(val) === -1 ? 'none' : 'table-row';
    }

    return {
      init: function() {
        var inputs = document.getElementsByClassName('light-table-filter');
        Arr.forEach.call(inputs, function(input) {
          input.oninput = _onInputEvent;
        });
      }
    };
  })(Array.prototype);

  document.addEventListener('readystatechange', function() {
    if (document.readyState === 'complete') {
      LightTableFilter.init();
    }
  });

})(document);


</script>




<input type="search" class="light-table-filter" data-table="order-table" placeholder="Search here ">

<div class="row">

<table id="myTable"  class="order-table table">
  <thead>
   <!-- <tr>
      <th>Vehicle_ID</th>
      <th>images</th>
      <th>Make</th>
      <th>Short_Model </th>
      <th> </th>
    </tr>

  -->
  </thead>
  <tbody>
    {% for car in cars %}

      <tr class="w30">

        <td>  <a href="{% url 'vehicle:detail' forloop.counter %}">{{ car.Vehicle_ID }}</a> </td>
         <td>  <img src="{{car.model_pic.url}}" width="200px"  height="200px" /></td>
        <td>{{ car.Make }}</td>
        
        <td>{{ car.Short_Model }}</td>
        <td>{{ car.Long_Model }}</td>
           <td>{{ car.Trim }}</td>
              <td> <b> Booking Available  :-  </b>{{ car.Curbookvehiclel_Available }}</td>
          <td> <a class="btn" href="{% url 'vehicle:detail' forloop.counter %}"> View Details</a></td>
      </tr>
    {% endfor %}
  </tbody>
</table>

{% if cars.has_other_pages %}
  <ul class="pagination">

    {% if cars.start_index%}
        <li> <a href="?page={{ cars.start_index }}"> First page</a> </li>
    {% endif %}

    {% if cars.has_previous %}
      <li><a href="?page={{ cars.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in cars.paginator.page_range %}
      {% if cars.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if cars.has_next %}
      <li><a href="?page={{ cars.next_page_number }}">&raquo;</a></li>
       <li> <a href="?page={{ cars.paginator.num_pages }}">last &raquo;</a> </li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}

    


  </ul>
{% endif %}

{% endblock %}

app/templates/contactus.html
{% extends "based.html" %}

{% block content %}

  
<div class="container">
	<div class="row">
 



      <div class="col-md-6 col-md-offset-3">
        <div class="well well-sm">
        	<p> Submit Your data,.</p>
               
<form method="POST" class="post-form">  
        {% csrf_token %}  
        {{ form.as_p }}  
        <button type="submit" class="save btn btn-default">Submit</button>  
    </form>  

</div>
</div>
</div>
</div>

    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d380510.68412994454!2d-88.01284404835026!3d41.833902495034614!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x880e2c3cd0f4cbed%3A0xafe0a6ad09c0c000!2sChicago%2C+IL%2C+USA!5e0!3m2!1sen!2sin!4v1531650226524" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

{% endblock %}

app/templates/my_car_list.html.html
my_car_list.html

app/templates/rental.html
{% extends "based.html" %}

{% block content %}

<script>
//custom js for book-now button
function bookme(thise){
id=thise.parentElement.parentElement.firstElementChild.textContent.slice(1);
document.location="/booknow?vid="+id
}
</script>
<script>
function myFunction() {
  var input, filter, table, tr, td, i;
  input = document.getElementById("myInput");
  filter = input.value.toUpperCase();
  table = document.getElementById("myTable");
  tr = table.getElementsByTagName("tr");
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("td")[0];
    if (td) {
      if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
        tr[i].style.display = "";
      } else {
        tr[i].style.display = "none";
      }
    }       
  }
}
</script>

  


<div class="container">
	<div class="row">
 


               
               <input type="text" id="myInput" placeholder="Search here" onkeyup="myFunction()" placeholder="Search for names..">

<table id="myTable" border="1" style="tr,td:padding:5px !important;" class="table table-striped custab">
  
  <tr> <th>Vehicle_ID: </th> <th> Make  </th> <th> Short_Model </th>  <th> trim </th><th> Currentl_Available</th> <th> Book </th></tr>
  {% for Car in car %}  

    <tr><td> {{Car.Vehicle_ID}}</td> 
    <td> {{Car.Make}}</td> 
    <td> {{Car.Short_Model}}</td> 
    <td> {{Car.Trim}}</td> 
    <td> {{Car.Currentl_Available}}</td> 
    
    
    
	<td>    <button onclick="bookme(this)"> book now</button> </td>

    </tr>
  
 {% endfor %} 


</table>
</div>
</div>


{% endblock %}

app/templates/view_booking.html
{% extends "based.html" %}

{% block content %}




  <p>The following record shows your booking history:</p>

  
<div class="container">
    <div class="row xcol-md-6 xcol-md-offset-2 custyle">
    <table class="table table-striped custab">
    <thead>
        <tr>
            <th>EntryID</th>
            <th>UID</th>
            <th>VID</th>
            <th>Make</th>
            <th>Short Model</th>
            <th>Long Model</th>
            <th>Trim</th>
            <th>Derivative</th>
            <th>Year introduced</th>
            <th>Year discontinued</th>
            <th>Currently Available</th>
			
        </tr>
    </thead>
	{% for entry in bookings %} 
            <tr>
                <td>{{entry.id}}</td>
                <td>{{entry.used_email}}</td>
                <td>{{entry.Vehicle_ID}}</td>
                <td>{{entry.Make}}</td>
                <td>{{entry.Short_Model}}</td>
                <td>{{entry.Long_Model}}</td>
                <td>{{entry.Trim}}</td>
                <td>{{entry.Derivative}}</td>
                <td>{{entry.Year_introduced}}</td>
                <td>{{entry.Year_discontinued}}</td>
                <td>{{entry.Currentl_Available}}</td>
            </tr>
	{% endfor %} 
    </table>
    </div>
</div>


{% endblock %}